### ISSUE TITLE
hi :)

### ISSUE THREAD

**Issue by stephenplusplus** [davidrekow/gcloud-node-scaffold#1]
<img width="739" alt="screen shot 2015-07-24 at 7 24 00 pm" src="https://cloud.githubusercontent.com/assets/723048/8886507/8dadab8a-3239-11e5-8491-11cca88909c1.png">

I'm working on gcloud-node, so let me know if you run into weird stuff or have any ideas how we can make integrations like these better.

Also, have you considered converting this into a [yeoman](http://yeoman.io) generator? It might help make it easier for others to use and save you some time from having to manually handle terminal input, etc.

Either way, just wanted to stop by and say this is pretty cool!

**Comment by rekow** [comment]
Hi :) Thanks for the fave and for all the work making node so easy to use on gcp!

I actually have yeoman open in another tab right now exploring that idea, it definitely seems the way to go. This was mostly born out of laziness as I got super tired of repeated copypasta, but once it was actually getting downloaded on npm I realized should probably do much more work to make it easy to use. Haven't used yeoman much personally but have of course heard plenty and it seems super simple!

I'm sure you've got your hands full with work on the platform, but if you have any suggestions I'd love input as well - looking to expand configurability re: build process (make/grunt/gulp etc., webpack/browserify etc.), template engine choices, storage backends (right now it defaults to the datastore) and front-end frameworks so I'll likely be looking to yeoman even more in the near future for much of the heavy lifting there.

Thanks man, stoked to be on GCP with node after settling for app engine python for so long :)

**Comment by stephenplusplus** [comment]
Thanks for the kind words! I think the easiest thing to do is choose the sanest, most common starting point possible. Users will always have their preferences (Grunt over Gulp, Sass over Less, CoffeeScript over vanilla, etc), and they will be able to make those changes after scaffolding.

In this case, I would probably check out [generator-gulp-webapp](https://github.com/yeoman/generator-gulp-webapp), which has a lot of good defaults, and consider incorporating some of them here or even [composing with](http://yeoman.io/authoring/composability.html).

The whole [Writing your own Yeoman generator](http://yeoman.io/authoring/) walkthrough is pretty helpful. There's also [generator-generator](https://github.com/yeoman/generator-generator) which will create a nice, plain generator for you to help you get started.

Let me know if you get stuck, and of course open issues if you run into issues anywhere along the way (gcloud or yeoman). I'm excited to type:

``` sh
$ yo gcloud
```

:)
